name: Feature Request Workflow
on:
  issues:
    types: [opened, labeled]
permissions:
  issues: write
  contents: read
  pull-requests: write
  project: write
jobs:
  feature_request_workflow:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'feature-request' || github.event.action == 'opened'
    env:
      BACKLOG_COLUMN_ID: ${{ secrets.BACKLOG_COLUMN_ID }}
      PRIORITY_COLUMN_ID: ${{ secrets.PRIORITY_COLUMN_ID }}
      FEATURE_LABEL: "feature-request"
      PRIORITY_LABEL: "priority"
      COMMENT: "Thank you for submitting a feature request! It has been added to our backlog for review."
    steps:
      # Step 1: Check and create required labels
      - name: Ensure Labels Exist
        uses: actions/github-script@v6
        with:
          script: |
            const labels = await github.issues.listLabelsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo
            });

            const existingLabels = labels.data.map(label => label.name);
            const requiredLabels = ["${{ env.FEATURE_LABEL }}", "${{ env.PRIORITY_LABEL }}"];

            for (const label of requiredLabels) {
              if (!existingLabels.includes(label)) {
                await github.issues.createLabel({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  name: label,
                  color: label === "${{ env.FEATURE_LABEL }}" ? "1d76db" : "d93f0b",  // Optional color codes
                  description: label === "${{ env.FEATURE_LABEL }}" ? "Feature request label" : "Priority label"
                });
              }
            }
      # Step 2: Add 'feature-request' label to new issues
      - name: Add Feature Label
        uses: ./.github/actions/add-label
        with:
          label: ${{ env.FEATURE_LABEL }}
      # Step 3: Move the issue to the Backlog column
      - name: Move to Backlog
        uses: ./.github/actions/move-to-column
        with:
          column_id: ${{ env.BACKLOG_COLUMN_ID }}
      # Step 4: Comment on the issue to acknowledge submission
      - name: Comment on Issue
        uses: ./.github/actions/comment-on-issue
        with:
          comment: ${{ env.COMMENT }}
  prioritize_feature:
    runs-on: ubuntu-latest
    needs: feature_request_workflow
    if: github.event.action == 'labeled' && github.event.label.name == 'priority'
    steps:
      # Step 5: Move to the priority column if marked with 'priority'
      - name: Move to Priority Column
        uses: ./.github/actions/move-to-column
        with:
          column_id: ${{ env.PRIORITY_COLUMN_ID }}
